config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/top", to: "static_pages#top"
  
  # helpfulの作成と削除
  post "/answers/:answer_id//helpful", to: "helpfuls#create", as: "create_helpful"
  delete "/answers/:answer_id/helpful", to: "helpfuls#destroy", as: "destroy_helpful"
  
  resources :users, except: [:index] do
    resource :relationships, only: [:create, :destroy]
  end
  # パスワード編集画面用
  get 'users/:id/edit_password', to: "users#edit_password", as: "edit_user_password"
  patch 'users/:id/update_password', to: "users#update_password", as: "update_user_password" 
  
  resources :posts, except: [:show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :questions, except: [:index] do
    resources :answers, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :helpfuls, dependent: :destroy
  has_many :answers, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  
  
  attr_accessor :remember_token
  before_save :email_downcase
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :username, presence: true, length: {maximum: 30 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :profile, length: {maximum: 200}
  validates :travel_period, length: {maximum: 30}
  validates :current_location, length: {maximum: 30}

  attachment :profile_image

  # 文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  #トークンをダイジェスト化してDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))  
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
    # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # 既にいいねしているか確認
  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  # 既に役立つを押しているか確認
  def already_helpful?(answer)
    self.helpfuls.exists?(answer_id: answer.id)
  end
  
  # 既に引数で渡されたuserをフォローしているか確認
  def already_following?(user)
    self.followings.include?(user)
  end
  
    private
    def email_downcase
      self.email = email.downcase
    end
    
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :edit_password, :update_password]
  
  def new
    @user = User.new
  end
  
  def create
    @user= User.new(create_user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "#{@user.username}さんは新規登録されました"
      follow_official_user
      redirect_to root_url
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    # コメント投稿用
    @comment = Comment.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      flash[:success]="#{@user.username}さんのプロフィールを更新しました"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end
  
  def edit_password
    @user = User.find(params[:id])
  end
  
  def update_password
    @user = User.find(params[:id])
    if @user.update(update_password_params)
      flash[:success]="#{@user.username}さんのパスワードを変更しました"
      redirect_to user_path(@user)
    else
      render "edit_password"
    end
  end

  private 
    def follow_official_user
      Relationship.create(followed_id: 1, follower_id: User.find_by(email: params[:user][:email]).id)
    end
  
    def create_user_params
      params.require(:user).permit(:username,:email, :password,
                                   :password_confirmation)
    end
    
    def update_user_params
      params.require(:user).permit(:username, :email, :profile_image, :profile,
                                   :travel_period, :current_location)
    end
    
    def update_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_basic_form.html.erb
<%= form_for (user), url: user_path(user) do |f| %>

    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :username, "名前", class: "label-control" %>
    <%= f.text_field :username, class: 'form-control' %>
     
    <%= f.label :email, "メールアドレス", class: "label-control" %>
    <%= f.email_field :email, class: 'form-control' %>
    
    <%= f.label :profile_image_id, "プロフィール画像", class: "label-control"%><br>
    <%= f.attachment_field :profile_image, class: "pl-3" %><br>
  
    <%= f.label :profile,"プロフィール", class: "label-control" %>　　　
    <%= f.text_area :profile, class: 'form-control' %>
    
    <%= f.label :travel_period, "旅歴", class: "label-control" %>
    <%= f.text_field :travel_period, class: 'form-control' %>
    
    <%= f.label :current_location, "現在地", class: "label-control" %>
    <%= f.text_field :current_location, class: 'form-control' %>
     
    <div class= "submit-position">
      <%= f.submit "プロフィールを更新", class: "btn btn-success" %>
    </div>  
<% end %>

app/views/users/_user_new_form.html.erb
  <%= form_for (user) do |f| %>

    <%= render "shared/error_messages", object: f.object %>
    
    <%= f.label :username, "名前", class: "label-control" %>
    <%= f.text_field :username, class: 'form-control' %>
  
    <%= f.label :email, "メールアドレス" , class: "label-control"%>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.label :password, "パスワード" , class: "label-control"%>
    <%= f.password_field :password, class: 'form-control' %>
  
    <%= f.label :password_confirmation, "パスワード確認" , class: "label-control"%>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    
    <div class= "submit-position">
      <%= f.submit "新規登録", class: "btn btn-success", id: "rspec_new_user_button" %>
    </div>  
  <% end %>

app/views/users/_user_password_form.html.erb
<%= form_for (user), url: update_user_password_path(user)  do |f| %>

    <%= render "shared/error_messages", object: f.object %>
    
    <%= f.label :password, "パスワード", class: "label-control" %>
    <%= f.password_field :password, class: 'form-control' %>
     
    <%= f.label :password_confirmation, "パスワード確認", class: "label-control"%>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  
    <div class= "submit-position">
      <%= f.submit "パスワードを変更", class: "btn btn-success" %>
    </div>  
<% end %>

app/views/users/edit.html.erb
  <!--render 'shared/error_messages', model: f.object %>-->
    <!--エラーが起きたのでコメントアウトしておく-->
<div id="container-with-menu">
  <section class="side-menu-container d-inline-block align-top">
    <ul class="list-group h6">
      <li><%= link_to "基本情報", edit_user_path(@user, ), class: " list-group-item" %></li>
      <li><%= link_to "パスワード設定", edit_user_path(@user, templete: "password"), class: "list-group-item" %></li>
    </ul>
  </section>      
  <section class="w800-container d-inline-block text-left">
  <% if params[:templete] == "password" %>
    <%= render "users/user_password_form", user: @user %>
  <% else %>  
    <%= render "users/user_basic_form", user: @user %>
  <% end %>
  </section>
</div>    

app/views/users/edit_password.html.erb
<div class="container-with-menu">
  <section class="side-menu-container d-inline-block align-top">
    <ul class="list-group h6">
      <li><%= link_to "基本情報", edit_user_path(@user, ), class: " list-group-item" %></li>
      <li><%= link_to "パスワード設定", edit_user_password_path(@user), class: "list-group-item" %></li>
    </ul>
  </section>      
  <section class="w800-container d-inline-block text-left">
    <%= render "users/user_password_form", user: @user %>
  </section>
</div>    

app/views/users/new.html.erb
<section class="w900-container">
  <h2>新規ユーザー登録</h2>
  <%= render "users/user_new_form", user: @user %>
  <div class="text-right">
    <%= link_to "既に登録済みの方はこちら", login_path %>
  </div>
  
</section>

app/views/users/show.html.erb
<section class="w1100-container">


  <section id ="profile-container" >
    <div class="d-flex flex-wrap ">
      <div class="col-lg-2 pl-0">
        <%= attachment_image_tag @user, :profile_image, class: "profile_image m-3", fallback: "no_image.jpg", size: '120x120', id: "rspec_user_path_profile_image" %>
      </div>
      <div class="col-lg-9 pl-5">
        <div class="d-flex align-items-start">
          <p class="mb-2 pr-3" id="profile-username" ><%= @user.username%></p>
          <% if @user.id == current_user.id  %>
            <%= link_to edit_user_path(@user), class: "mt-1 pl-2 profile-edit-button" do%>
              <span>プロフィールを編集</span><i class="fas fa-pen post-font-awesome px-1"></i>
            <% end %>
          <% else%>
            <div id="ajax-follow-button">
              <%= render "relationships/follow", user: @user%>
            </div>
        <% end %>
          
        </div>
          <div class="d-flex fs-13 mb-2">
            <p class="col-3 mb-0 pl-0 ce-pointer" id="follower-modal-open">フォロワー<span id="ajax-followers-number"><%= @user.followers.count %></span>人</p>
            <p class="col-3 mb-0 pl-0 ce-pointer" id="following-modal-open">フォロー<span id="ajax-followings-number"><%= @user.followings.count %></span>人</p>
          </div>
          <p id="profile-body" class="mb-2"><%= @user.profile %></p>
          <div class="d-flex text-secondary fs-12">
            <p class="col-3 pl-0"><i class="fa-solid fa-compass pr-1"></i><%= @user.travel_period %></p>
            <p class="col-3 pl-0"><i class="fa-solid fa-location-dot pr-1"></i><%= @user.current_location%></p>
          </div>  
      </div>
    </div>
    <!--フォロー一覧モーダル-->
    <span id="ajax-follower-modal"><%= render "relationships/follow_list_modal", follow: "follower", follows: @user.followers, title: "フォロワー" %></span>
    <span id="ajax-folloer-modal"><%= render "relationships/follow_list_modal", follow: "following", follows: @user.followings, title: "フォロー中" %></span>
    
  </section>

  <section id="profile-posts-container">
    <ul class="d-flex flex-wrap p-0">
      <% @user.posts.reverse_each do |post| %>
        <li data-toggle="modal" style=""data-target=".bd-example-modal-lg-<%=post.id%>">
          <%= attachment_image_tag post, :post_image, id: "profile-posts-posts"  %>
        </li>
        <!--モーダル中身-->
        <%= render "shared/post_modal", post: post, comment: @comment %>
      <% end %>
    </ul>
  </section>
</section>