config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/top", to: "static_pages#top"
  
  # helpfulの作成と削除
  post "/answers/:answer_id//helpful", to: "helpfuls#create", as: "create_helpful"
  delete "/answers/:answer_id/helpful", to: "helpfuls#destroy", as: "destroy_helpful"
  
  resources :users, except: [:index] do
    resource :relationships, only: [:create, :destroy]
  end
  # パスワード編集画面用
  get 'users/:id/edit_password', to: "users#edit_password", as: "edit_user_password"
  patch 'users/:id/update_password', to: "users#update_password", as: "update_user_password" 
  
  resources :posts, except: [:show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :questions, except: [:index] do
    resources :answers, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :helpfuls, dependent: :destroy
  validates :answer_body, presence: true, length: {maximum: 300}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :post_categories
has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment_body, presence: true, length: {maximum: 300}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/helpful.rb
class Helpful < ApplicationRecord
  belongs_to :user
  belongs_to :answer
  validates_uniqueness_of :answer_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :post_categories 
    has_many :categories, through: :post_categories
    attachment :post_image
    validates :title, presence: true, length: {maximum: 30 }
    validates :post_image, presence: true
    validates :body, length: {maximum: 300}
    validates :location, length: {maximum: 30 }
end
  

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :question_title, presence: true, length: {maximum: 30 }
  validates :question_body, presence: true, length: {maximum: 300 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :helpfuls, dependent: :destroy
  has_many :answers, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  
  
  attr_accessor :remember_token
  before_save :email_downcase
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :username, presence: true, length: {maximum: 30 }
  VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :profile, length: {maximum: 200}
  validates :travel_period, length: {maximum: 30}
  validates :current_location, length: {maximum: 30}

  attachment :profile_image

  # 文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  #トークンをダイジェスト化してDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))  
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
    # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # 既にいいねしているか確認
  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  # 既に役立つを押しているか確認
  def already_helpful?(answer)
    self.helpfuls.exists?(answer_id: answer.id)
  end
  
  # 既に引数で渡されたuserをフォローしているか確認
  def already_following?(user)
    self.followings.include?(user)
  end
  
    private
    def email_downcase
      self.email = email.downcase
    end
    
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/helpfuls_helper.rb
module HelpfulsHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if (user_id = session[:user_id]) #代入
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        session[:user_id] = user.id
        @current_user = user
      end
    end
  end  
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<!--変数名モデルを変更する-->
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <li><%= object.errors.count %>件のエラー</li>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash%>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %> 
<% end %> 

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <% if logged_in? %>
      <%= link_to "Sharevel", root_path, class: "navbar-brand", id: "sharevel-footer" %>
    <% else %>
      <%= link_to "Sharevel", top_path, class: "navbar-brand", id: "sharevel-footer" %>
    <% end %>
  
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "ホーム画面へ", root_path, class: "nav-link" %>
          </li>
        <% else %>  
          <li class="nav-item">
            <%= link_to "新規登録へ", new_user_path, class: "nav-link" %>
          </li>
        <% end %>  
        <li class="nav-item">
          <%= link_to "Sharevelとは", top_path , class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>  
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <% if logged_in?%>
      <%= link_to "Sharevel", root_path, class: "navbar-brand", id: "sharevel-header"%>
    <% else %>
      <%= link_to "Sharevel", top_path, class: "navbar-brand", id: "sharevel-header"%>
    <% end %>
  
    <div class="collapse navbar-collapse justify-content-end " id="navbarSupportedContent">
      <% if logged_in? %>
      <!--ログイン時-->
      <ul class="navbar-nav">
      <%= link_to root_path do %>
        <li class="nav-item">
          <div>
            <button class="dropdown">
              投稿を一覧<i class="fa-solid fa-earth-americas fa-lg pl-2"></i>
            </button>
          </div>
        </li>
      <% end %>
        <li class="nav-item">
          <div class="dropdown">
            <button class="dropdown-toggle"
                    type="button"  data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
              投稿をする<i class="fa fa-edit fa-lg pl-2 "></i> 
            </button>
            <div class="dropdown-menu">
              <%= link_to "旅をシェア", new_post_path, class: "dropdown-item text-success"%>      
              <%= link_to "旅人に質問", new_question_path, class: "dropdown-item text-success" %>
            </div>
          </div>
        </li>
        
        <li class="nav-item">
          <!--ドロップダウン用-->
          <div class="dropdown open">
            <button class="dropdown-toggle"
                    type="button"data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
              マイページ<i class="fa fa-user fa-lg pl-2"></i> 
            </button>
            <div class="dropdown-menu">
              <%= link_to "プロフィール", user_path(current_user), class: "dropdown-item"%>      
              <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </li>
        <!--ログアウト時-->
      <% else %>
        <button class="nav-item py-2">
          <%= link_to "新規登録", new_user_path, class: "nav-link" %>
        </button>   
        <button class="nav-item py-2">
          <%= link_to "ログイン", login_path, class: "nav-link" %>
        </button>   
      <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_post_modal.html.erb
      <div class="modal fade bd-example-modal-lg-<%=post.id%>" tabindex="-1" role="dialog"
           aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
    
            <section class = "list-container list-modal my-5">
                <%= link_to user_path(post.user) do %>
                  <%= attachment_image_tag post.user, :profile_image, class: "profile_image my-2 mr-2 ml-3", fallback: "no_image.jpg", size: '40x40' %>
                <% end %>
              <div class="d-inline-block align-middle">
                <%= link_to user_path(post.user) do %>
                  <p class="post-top-element d-inline list-username"><%= post.user.username %></p>
                <% end %>
                <p class="list-top-element d-inline post-location"><%= post.location %></p>
                <p class="list-top-element post-title mb-0"><%= post.title %></p>
              </div>
              <%= link_to post_favorites_path(post), method: :post, remote: true do %>
                <%= attachment_image_tag post, :post_image, class: "d-block", style: "margin: 0 auto ;", size: '540x540' %>
              <% end %>
              <div class="ml-4">
                <%= simple_format post.body, class: "post-body pt-2" %>
                <% post.categories.each do |category| %><!--カテゴリーをハッシュタグで表示-->
                  <%= link_to "##{category.name}", root_path(name: category.name), class: "post-category-name-tag" %>
                <% end %>
                <p class = "pb-1 list-created-at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
                <ul class="mb-0 pr-3 pb-1 text-right">
                  <div class="post-font-awesome d-inline-block" id="ajax-favorite-post-<%= post.id%>">
                    <%= render "favorites/favorite", post: post %>
                  </div>
                  <% if current_user.id == post.user.id%>
                      <%= link_to edit_post_path(post), class: " d-inline-block" do %>
                          <i class="fas fa-pen fa-lg post-font-awesome"></i>
                      <% end %>
                      <%= link_to post_path(post), class: "d-inline-block", data: {confirm: "投稿を削除しますか？"}, method: :delete do %>
                        <i class="far fa-trash-alt fa-lg post-font-awesome"></i>
                      <% end %>
                  <% end %>
                </ul>
              
              <!--コメントの作成フォーム-->
              <div class= "post-comment-container">
                <%= form_with model: [post, comment], method: :post do |f| %>
                  <%= f.text_area :comment_body, placeholder: "コメント" , class: "post-comment-create-textarea" %>
                  <%= f.submit "投稿する", class: "post-comment-create-input"%>
                <% end %>
              <!--コメントの表示-->
                <div id="ajax-for-comments">
                  <%= render "comments/comments", post: post %>
                </div>
              </div>
          </div>
        </div>
      </div>   