config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/top", to: "static_pages#top"
  
  # helpfulの作成と削除
  post "/answers/:answer_id//helpful", to: "helpfuls#create", as: "create_helpful"
  delete "/answers/:answer_id/helpful", to: "helpfuls#destroy", as: "destroy_helpful"
  
  resources :users, except: [:index] do
    resource :relationships, only: [:create, :destroy]
  end
  # パスワード編集画面用
  get 'users/:id/edit_password', to: "users#edit_password", as: "edit_user_password"
  patch 'users/:id/update_password', to: "users#update_password", as: "update_user_password" 
  
  resources :posts, except: [:show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :questions, except: [:index] do
    resources :answers, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :helpfuls, dependent: :destroy
  validates :answer_body, presence: true, length: {maximum: 300}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_answer_user,   only: :destroy
  before_action :define_question
  
  def create
    @answer = current_user.answers.build(answer_params)
    @answer.question_id = @question.id
    @answer.save
    respond_to do |format|
      format.html { redirect_back fallback_location: question_path(@question) }
      format.js
    end  
  end
  
  def destroy
    Answer.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: question_path(@question) }
      format.js
    end  
  end
  
  
  private
  
  def answer_params
    params.require(:answer).permit(:answer_body)
  end
  
  def define_question
    @question = Question.find(params[:question_id])
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.erb
  <!--cssに関しては質問のものを使用-->
<% question.answers.each do |answer| %>
<section class="question-show-answer-container">
  <div>
    <%= link_to user_path(answer.user) do %>
      <%= attachment_image_tag answer.user, :profile_image, class: "profile_image mt-3 mr-2 ml-3 mb-0", fallback: "no_image.jpg", size: '40x40' %>
    <% end %>
    <div class="d-inline-block align-middle pt-3">
      <%= link_to user_path(answer.user) do %>
        <p class="list-top-element d-inline list-username pr-0 "><%= answer.user.username %></p>
      <% end %><span>さんの回答</span>
    </div>
  </div>
    <%= simple_format answer.answer_body, class: "question-show-question-body" %>
  <div class="text-right">
    <p class = "question-created-at mb-0"><%= answer.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    <div>
       <span id="ajax-helpful-answer-<%= answer.id%>"><%= render "helpfuls/helpful", answer: answer %></span>
      <% if current_user == answer.user %>
        <%= link_to question_answer_path(question, answer), data: {confirm: "回答を削除しますか？"}, method: :delete, remote: true do %>
          <i class="far fa-trash-alt pr-3 pb-2"></i>
        <% end %>
      <% end %>  
    </div>
  </div>
</section>
<% end %>

app/views/answers/create.js.erb
<!--render内を更新-->
$("#ajax-for-answers").html("<%= j(render 'answers/answers', question: @question)%>")
<!--入力欄を空にする-->
$(".question-answer-create-textarea").val('');
<!--回答数を更新する-->
$("#ajax-count-answers").html("<%= @question.answers.count%>")

app/views/answers/destroy.js.erb
<!--render内を更新-->
$("#ajax-for-answers").html("<%= j(render 'answers/answers', question: @question)%>")
<!--回答数を更新する-->
$("#ajax-count-answers").html("<%= @question.answers.count%>")