config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/top", to: "static_pages#top"
  
  # helpfulの作成と削除
  post "/answers/:answer_id//helpful", to: "helpfuls#create", as: "create_helpful"
  delete "/answers/:answer_id/helpful", to: "helpfuls#destroy", as: "destroy_helpful"
  
  resources :users, except: [:index] do
    resource :relationships, only: [:create, :destroy]
  end
  # パスワード編集画面用
  get 'users/:id/edit_password', to: "users#edit_password", as: "edit_user_password"
  patch 'users/:id/update_password', to: "users#update_password", as: "update_user_password" 
  
  resources :posts, except: [:show] do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :questions, except: [:index] do
    resources :answers, only: [:create, :destroy]
  end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :post_categories 
    has_many :categories, through: :post_categories
    attachment :post_image
    validates :title, presence: true, length: {maximum: 30 }
    validates :post_image, presence: true
    validates :body, length: {maximum: 300}
    validates :location, length: {maximum: 30 }
end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :logged_in_user_for_root, only: :index
  before_action :logged_in_user, except: :index
  before_action :correct_post_user, only: [:edit, :update, :destroy]
  before_action :define_big_categories, only: [:edit, :new, :index, :create, :update]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "#{@post.title}を投稿しました"
      redirect_to root_url
    else
      render "new"
    end
  end
  
  def index
    unless logged_in?
      redirect_to top_path
    end
    # 投稿を表示用インスタンス変数
    define_lists_by_params
    #ページ右の最新質問用インスタンス変数
    @right_questions = Question.order(id: :DESC).first(5)
    # モーダルコメント作成用インスタンス変数
    @comment = Comment.new
    @lists = @lists.paginate(page: params[:page], per_page: 15)
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "#{@post.title}を更新しました"
      redirect_to root_url
    else
      render "edit"
    end
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:success] = "投稿を削除しました"
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :post_image, :location, category_ids: [])
  end
  
  def logged_in_user_for_root
    unless  logged_in?
      # フラッシュメッセージを表示しない
      redirect_to new_user_path
    end
  end

  
  def define_lists_by_params
    if params[:name]
      category = Category.find_by(name: params[:name])
      @lists = category.posts.sort {|a, b| b.id <=> a.id}
    elsif params[:big_category]
      categories = Category.where(big_category: params[:big_category])
      @lists = []
      categories.each do |category|
        @lists.push(*category.posts)
      end
    else
      users = current_user.followings
      @lists = []
      users.each do |user|
        @lists.push(*user.posts, *user.questions)
      end
      @lists.push(*current_user.posts, *current_user.questions)
      @lists.sort!{ |a, b| b.created_at <=> a.created_at }
    end
  end
  
  def define_big_categories
    bc_names = %w(国内旅行 アジア オセアニア 北アメリカ ヨーロッパ その他)
    @big_categories = Category.where(big_category: bc_names).group_by(&:big_category).values
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts_form.html.erb
<%= form_for (@post) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  
  <div class="d-flex label-control  align-items-start">
    <%= f.label :title, "タイトル" %>
    <span class="essential-label">必須</span>
  </div>
  <%= f.text_field :title, class: 'form-control' %>
  
  <%= f.label :location, "場所", class: "label-control"%>
  <%= f.text_field :location, class: 'form-control' %>
   
  <div class="d-flex label-control  align-items-start">
    <%= f.label :post_image, "写真" %>
    <span class="essential-label">必須</span>
  </div>
  <%= f.attachment_field :post_image %><br>
  
  <!--カテゴリーチェックボックスの表示-->
  <%= f.label :category_id, "カテゴリー", class: "label-control" %><br>
  <div>
    <% big_categories.each do |big_category| %>
      <div>
        <div class="category-dropdown-button" id="form-category-dropdown-<%= big_category[0].big_category %>">
          <input type="button" value="<%= big_category[0].big_category %>">
          <i class="fa fa-xs fa-light fa-chevron-down"></i>
        </div>
        <div id="form-category-dropdown-item-<%= big_category[0].big_category %>" class="category-dropdown-items">
          <%= f.collection_check_boxes :category_ids, big_category, :id , :name do |b| %>
            <div class="each-category-dropdown-item">
              <%= b.check_box class: "category-dropdown-item-checkbox"%>
              <%= b.text %>
            </div>  
          <% end %>
        </div>
      </div>
          <!--ドロップダウン用のjquery-->
          <script>
            $(function(){
              $("#form-category-dropdown-item-<%= big_category[0].big_category %>").hide();
              $("#form-category-dropdown-<%= big_category[0].big_category %>").click(function(){
                $("#form-category-dropdown-item-<%= big_category[0].big_category %>").toggle();
              });
            });
          </script>
    <% end %>
  </div>
  

  <%= f.label :body, "内容", class: "label-control" %>　　　
  <%= f.text_area :body, class: 'form-control' %>
  <div class="submit-position">
    <%= f.submit locals[:button_text] , class: "btn btn-success", id: "post_button" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section class = "w1100-container">
  <h1>投稿編集</h1>
  <%= render "posts/posts_form", locals: {button_text: "更新" }, big_categories: @big_categories %>
</section>

app/views/posts/index.html.erb
<section class="list-header-image">
</section>  

<section class="list-page-container d-flex">
  <section class="list-left-container">
    <div class="left-category-choose-container">
      <p class="font-weight-bold text-success h6 pb-1 pl-3 pt-1">カテゴリーから見つける</p>
        <% @big_categories.each do |big_category|%>
            <p  class= "left-category-choose-big-categories"><%= link_to big_category[0].big_category, root_path(big_category: big_category[0].big_category) %>
            <i class="fa fa-chevron-down pl-3 " id= "left-category-dropdown-<%= big_category[0].big_category %>"></i></p>
            <% big_category.each do |category|%>
              <div id= "left-category-dropdown-item-<%= big_category[0].big_category %>">
                <%= link_to category.name, root_path(name: category.name), class: "left-category-choose-name" %>
              </div>
          <% end %>
        <!--ドロップダウン用-->
          <script>
            $(function(){
              $("#left-category-dropdown-item-<%= big_category[0].big_category %>").hide();
              $("#left-category-dropdown-<%= big_category[0].big_category %>").click(function(){
                $("#left-category-dropdown-item-<%= big_category[0].big_category %>").toggle();
              });
            });
          </script>
      <% end %>
    </div>
    
      
  </section>
  <!--画面中央のcontainer-->
  <section class="list-center-container">
      
    <!--投稿一覧-->
    <% @lists.each do |list| %>
        <!--写真付き投稿-->
      <% if list.class == Post %>
        <section class = "list-container ">
            <%= link_to user_path(list.user) do %>
              <%= attachment_image_tag list.user, :profile_image, class: "profile_image my-2 mr-2 ml-3", fallback: "no_image.jpg", size: '40x40' %>
            <% end %>
          <div class="d-inline-block align-middle">
            <%= link_to user_path(list.user) do %>
              <p class="post-top-element d-inline list-username"><%= list.user.username %></p>
            <% end %>
              <p class="post-top-element d-inline post-location"><%= list.location %></p>
              <p class="post-top-element post-title mb-0"><%= list.title %></p>
          </div>
          <span data-toggle="modal" data-target=".bd-example-modal-lg-<%=list.id%>">
            <!--spanはモーダル表示ボタンのため  -->
              <%= attachment_image_tag list, :post_image, class: "d-block", style: "margin: 0 auto ;", size: '540x540' %>
          </span>
          <div class="mx-4">
            <%= simple_format list.body, class: "post-body pt-2" %>
            <% list.categories.each do |category| %><!--カテゴリーをハッシュタグで表示-->
              <%= link_to "##{category.name}", root_path(name: category.name), class: "post-category-name-tag" %>
            <% end %>
            <p class = "pb-1 list-created-at"><%= list.created_at.strftime("%Y-%m-%d %H:%M") %></p>
        </section>
        
        <!--投稿写真を押したときよう-->
        <%= render "shared/post_modal", post: list, comment: @comment %>
        
        
        
        
      <!--質問の投稿      -->
      <% elsif list.class == Question %> 
        <section class="list-container ">
            <%= link_to user_path(list.user) do %>
              <%= attachment_image_tag list.user, :profile_image, class: "profile_image mt-3 mx-2 mb-0", fallback: "no_image.jpg", size: '40x40' %>
            <% end %>
          <div class="d-inline-block align-middle pt-3">
            <%= link_to user_path(list.user) do %>
              <p class="list-top-element d-inline list-username pr-0 "><%= list.user.username %></p>
            <% end %><span>さんの質問</span><i class="fa fa-question-circle "></i> 
  
            <%= link_to question_path(list)  do %>
                <p class="list-top-element list-question-title "><%= list.question_title %></p>
            <% end %>
          </div>
            <p class="list-question-body"><%= list.question_body %></p>
          <div>
            <p class = "pb-1 list-created-at"><%= list.created_at.strftime("%Y-%m-%d %H:%M") %></p>
            <div class="text-right">
              <p class="list-created-at d-inline-block pr-3" style="font-size:12px;"><%= list.answers.count %>件の回答</p>
              <% if current_user == list.user%>
                <%= link_to question_path(list), class: "d-inline-block pr-2", data: {confirm: "質問を削除しますか？"}, method: :delete do %>
                  <i class="far fa-trash-alt post-font-awesome"></i>
                <% end %>
              <% end %>  
                
            </div>
          </div>             
        </section>
      <% end %>
    <% end %>

    <%= will_paginate @lists%>
  </section>
  
  <section class="list-right-container">
    
    
    <!--プロフィールの表示-->
    <% if logged_in? %>
    <section class="list-right-profile-show-container py-2 mb-4">
      <div class="py-2">
        <div class="d-flex py-2 ">
          <div class="col-3">
            <%=link_to user_path(current_user) do  %>
            <%= attachment_image_tag current_user, :profile_image, class: "profile_image", fallback: "no_image.jpg", size: '60x60' %>
            <% end %>
          </div>
          <div class="col-9">
            <p class="d-inline-block"><%= link_to current_user.username, user_path(current_user) %></p>
            <%= link_to edit_user_path(current_user), class: "pl-2 profile-edit-button fs-10" do%>
              <span>編集</span><i class="fas fa-pen post-font-awesome px-1 fs-10"></i>
            <% end %>
            <p class="fs-10 mt-1">投稿<%= current_user.posts.count%>件</p>
            <div class="d-flex fs-11 mt-1">
              <p class="col-6 pl-0 ce-pointer" id="self-follower-modal-open">フォロワー<%= current_user.followers.count %>人</p>
              <p class="col-6 pl-0 ce-pointer" id="self-following-modal-open">フォロー<%= current_user.followings.count%>人</p>
            </div>
          </div>
        </div>
        <p class="fs-12 px-4 py-2"><%= current_user.profile %></p>
        <div class="d-flex flex-wrap px-4 pb-2 text-secondary fs-10">
          <p class="col-6 pl-0"><i class="fa-solid fa-compass pr-1"></i><%= current_user.travel_period %></p>
          <p class="col-6 pl-0"><i class="fa-solid fa-location-dot pr-1"></i><%= current_user.current_location%></p>
        </div>
      </div>
          <!--フォロー一覧モーダル-->
      <%= render "relationships/follow_list_modal", follow: "self-follower",follows: current_user.followers, user: current_user, title: "フォロワー" %>
      <%= render "relationships/follow_list_modal", follow: "self-following",follows: current_user.followings, user: current_user, title: "フォロー中" %>
    </section>
    <% end %>
    
    <!--最新の質問表示-->
    <section>
      <div style="font-weight: 600;">最新の質問に答える</div>
        <% num =0 %>
        <% @right_questions.each do |question| %>
        <% num +=1 %>
          <div class="list-right-question-list-container">
            <%=link_to question_path(question), class: "list-right-question-list" do %>
              <div>
                <p><%= num %>．<span style="font-weight:500;"><%= question.user.username %></span>さん</p>
                <p><%= question.question_title %></p>
                <p class="list-right-question-list-answer-count"><%= question.answers.count %>件の回答</p>
              </div>
            <% end %>
              <div class="text-right list-right-question-list-created-at">
                <p class="d-inline-blockm-0"><%= question.created_at.strftime("%Y-%m-%d") %></p>
              </div>  
          </div>
        <% end %>
    </section>  
  </section>
</section>
    

app/views/posts/new.html.erb
<section class = "w900-container">
  <h2>新規投稿</h2>
  <%= render "posts/posts_form", locals: {button_text: "旅をシェア" },  big_categories: @big_categories %>
</section>